name: Angular Auto Care App

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/auto-care

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
